"""
Core data generation logic
"""

from .generators import (
    USER_TEMPLATE,
    ECOM_TEMPLATE,
    FINANCIAL_TEMPLATE,
    HEALTHCARE_TEMPLATE,
    IOT_SENSOR_TEMPLATE,
    PRODUCT_CATALOG_TEMPLATE,
    NLP_TEXT_TEMPLATE,
    WEB_ANALYTICS_TEMPLATE,
    IMAGE_METADATA_TEMPLATE,
    EDU_STUDENT_TEMPLATE,
    generate_from_template
)

__all__ = [
    'USER_TEMPLATE',
    'ECOM_TEMPLATE',
    'FINANCIAL_TEMPLATE',
    'HEALTHCARE_TEMPLATE',
    'IOT_SENSOR_TEMPLATE',
    'PRODUCT_CATALOG_TEMPLATE',
    'NLP_TEXT_TEMPLATE',
    'WEB_ANALYTICS_TEMPLATE',
    'IMAGE_METADATA_TEMPLATE',
    'EDU_STUDENT_TEMPLATE',
    'generate_from_template'
]
